minimum_single: 20
minimum_multiple: 1
disable_search_threshold: 0
minimum_width: 300
use_relative_width: false
jquery_selector: select
search_contains: false
disable_search: false
allow_single_deselect: true
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
max_shown_results: null
disabled_themes:
  seven: '0'
chosen_include: 0
_core:
  default_config_hash: 2eOlYm2vQ7YYi7vT6plulHOFPYjs8sQDwoAvdz78Lws
