cache:
  http:
    s_maxage: 86400
    404_max_age: 300
    302_max_age: 300
    301_max_age: 300
    5xx_max_age: 300
    stale_while_revalidate: 60
    stale_if_error: 60
    vary: ''
  surrogate:
    maxage: 86400
    nostore: null
_core:
  default_config_hash: r_BkkPiZwRPZ06-zgJuklP0aj0NNSLzsLxPXYoOsfsk
