css_structural: 0
css_colors: 0
backgrounds_full: 1
color_variants:
  -
    name: grey
    foreground: '#303030'
    background: '#e5e5e5'
    link: '#de0055'
    hover: '#10BFFF'
  -
    name: spot-1
    foreground: '#ffffff'
    background: '#10BFFF'
    link: '#ffffff'
    hover: '#ffffff'
  -
    name: spot-2
    foreground: '#ffffff'
    background: '#DE0055'
    link: '#ffffff'
    hover: '#ffffff'
_core:
  default_config_hash: quHmnUotHbpcvN6AHvCV--6HbJAAr4_m6rEsvqWHqeI
