link_text: ''
legal_disclaimer: '28'
more_info_page: '26'
company_name: 'Dropsolid Rocketship Profile'
privacy_policy: '27'
langcode: en
_core:
  default_config_hash: 21d5hqyB7dOCABzQixLxVUA_I8q8NIJROpJDKn3jUSw
